Add CI config (disabled) Fedora 36 with OpenSSL
Disabled as for now the compilation fails due to changes in OpenSSL API:
one hard error as well as many deprecation warnings.

/__w/rnp/rnp/src/lib/crypto/dsa_ossl.cpp:291:28: error: invalid conversion from ‘const dsa_st*’ to ‘DSA*’ {aka ‘dsa_st*’} [-fpermissive]
  291 |     dsa = EVP_PKEY_get0_DSA(pkey);
      |           ~~~~~~~~~~~~~~~~~^~~~~~
      |                            |
      |                            const dsa_st*

Bug: https://github.com/rnpgp/rnp/issues/1617