ci: Disable (sanitize,beta) combination in tests for CentOS 8
It is causing build errors of GPG (GnuPG v2.3.0-beta983):

	libcommon.a(libcommon_a-iobuf.o):(.bss+0x8): multiple definition of `iobuf_debug_mode'
	t-iobuf.o:(.bss+0x0): first defined here
	clang-11: error: linker command failed with exit code 1 (use -v to see invocation)