Make CLIError printable
Before, after a CLI test fails, all you saw was

    cli_common.CLIError: <unprintable CLIError object>

It was due to a runtime error during __str__() method execution.