ci: Allow CentOS 7 to build with botan2-2.17.3 for now
Trying to build botan2-2.18.2 would result in the following error:

```
2021-10-27T10:56:15.0795568Z src/lib/hash/sha3/sha3.cpp:41:42: error: converting to ‘std::tuple<long unsigned int, long unsigned int, long unsigned int, long unsigned int, long unsigned int>’ from initializer list would use explicit constructor ‘constexpr std::tuple< <template-parameter-1-1> >::tuple(_UElements&& ...) [with _UElements = {long unsigned int, long unsigned int, long unsigned int, long unsigned int, long unsigned int}; <template-parameter-2-2> = void; _Elements = {long unsigned int, long unsigned int, long unsigned int, long unsigned int, long unsigned int}]’
2021-10-27T10:56:15.0797470Z        A[4] ^ A[9] ^ A[14] ^ A[19] ^ A[24]};
2021-10-27T10:56:15.0797821Z                                           ^
2021-10-27T10:56:15.1581937Z make: *** [build/obj/lib/hash_sha3.o] Error 1
2021-10-27T10:56:15.1588358Z make: *** Waiting for unfinished jobs....
2021-10-27T10:56:15.2739426Z ##[error]Process completed with exit code 2.
2021-10-27T10:56:15.2857574Z Post job cleanup.
2021-10-27T10:56:15.2864385Z ##[command]/usr/bin/docker exec  a870fb98493815c819b951b87419840bcbb38319cbae4c8f6b252ca25f53ff1b sh -c "cat /etc/*release | grep ^ID"
```

which I suspect is due to outdated GCC version in CentOS 7
(gcc-c++-4.8.5-44.el7.x86_64).